---
title: "STA 221 - Regression Analysis: Theory and Applications"
navbar: false
editor: visual
freeze: false
---

*This page contains an outline of the topics, content, and assignments for the semester. Note that this schedule will be updated as the semester progresses, with all changes documented here.*

```{r}
#| echo: false
#| message: false
#| warning: false

library(googlesheets4)
library(gt)
library(tidyverse)
gs4_deauth()
d <- read_sheet("https://docs.google.com/spreadsheets/d/1A4OXbBUbQG4ssnrj_HzD6Pcp2gPE1Q3JoSLeB_lSeM8/edit?usp=sharing", sheet = "Sheet1")
```

::: column-screen-right
```{r}
#| echo: false

d |>
  select(-`Maria's notes`) |>
  mutate(
    date = as.Date(date),
    week = ifelse(is.na(week), "", week),
    dow = ifelse(is.na(dow), "", dow)
  ) |>
  gt() |>
  text_transform(cells_body(columns = c(prepare)),
    fn = function(x) {
      ifelse(is.na(x), fontawesome::fa("book", fill_opacity = 0.1),
        glue::glue("<a href = {x}>{fontawesome::fa('book')}</a>")
      )
    }
  ) |>
  text_transform(cells_body(columns = c(slides)),
    fn = function(x) {
      ifelse(is.na(x), fontawesome::fa("laptop", fill_opacity = 0.1),
        glue::glue("<a href = {x}>{fontawesome::fa('laptop')}</a>")
      )
    }
  ) |>
    text_transform(cells_body(columns = c(notes)),
    fn = function(x) {
      ifelse(is.na(x), fontawesome::fa("file-pen", fill_opacity = 0.1),
        glue::glue("<a href = {x}>{fontawesome::fa('file-pen')}</a><br>")
      )
    }
  ) |>
  text_transform(cells_body(columns = c(ae)),
    fn = function(x) {
      ifelse(is.na(x), fontawesome::fa("users", fill_opacity = 0.1),
        glue::glue("<a href = {x}>{fontawesome::fa('users')}</a>")
      )
    }
  ) |>
  text_transform(cells_body(columns = c(hw)),
    fn = function(x) {
      ifelse(is.na(x), fontawesome::fa("pen-to-square", fill_opacity = 0.1),
        glue::glue("<a href = {x}>{fontawesome::fa('pen-to-square')}</a>")
      )
    }
  ) |>
  text_transform(cells_body(columns = c(lab)),
    fn = function(x) {
      ifelse(is.na(x), fontawesome::fa("file-code", fill_opacity = 0.1),
        glue::glue("<a href = {x}>{fontawesome::fa('file-code')}</a>")
      )
    }
  ) |>
  # text_transform(cells_body(columns = c(exam)),
  #   fn = function(x) {
  #     ifelse(is.na(x), fontawesome::fa("square-check", fill_opacity = 0.1),
  #       glue::glue("<a href = {x}>{fontawesome::fa('square-check')}</a>")
  #     )
  #   }
  # ) |>
  text_transform(cells_body(columns = c(project)),
    fn = function(x) {
      ifelse(is.na(x), fontawesome::fa("chart-line", fill_opacity = 0.1),
        glue::glue("<a href = {x}>{fontawesome::fa('chart-line')}</a>")
      )
    }
  ) |>
  fmt_date(date, date_style = 30) |>
  sub_missing(columns = c(date, topic, due), missing_text = "") |>
  cols_align(
    align = "center", 
    columns = c(week, dow, prepare, slides,notes, ae, hw, lab,project)
    ) |>
  cols_align(
    align = "left", 
    columns = c(date, topic, due)
    ) |>
  tab_style(
    style = cell_borders(
      sides = "right",
      color = "#D3D3D3",
      style = "solid"
    ),
    locations = cells_body(
      columns = c(date, topic, prepare, ae, lab, project)
    )
  ) |>
  cols_width(
    c(prepare, slides, notes, ae, hw, lab, project) ~ px(125)
 )


```
:::
