---
title: "Course support"
---

We expect everyone will have questions at some point in the semester, so we want to make sure you can identify when that is and feel comfortable seeking help.

## Lectures and labs

If you have a question during lecture or lab, feel free to ask it! There are likely other students with the same question, so by asking you will create a learning opportunity for everyone.

## Office hours

The teaching team is here to help you be successful in the course. You are encouraged to attend office hours during the times posted on Canvas to ask questions about the course content and assignments. A lot of questions are most effectively answered in-person, so office hours are a valuable resource. I encourage you to take advantage of them!

Make a pledge to stop by office hours at least once during the first three weeks of class. If you truly have no questions to ask, just stop by and say hi and introduce yourself. You can find a list of the teaching team's office hours on Canvas.

## Ed Discussion

Outside of class and office hours, any general questions about course content or assignments should be posted on Ed Discussion. There is a chance another student has already asked a similar question, so please check the other posts on Ed Discussion before adding a new question. If you know the answer to a question that is posted, I encourage you to respond!

## Email

If you have questions about personal matters that are not appropriate for the class discussion forum (e.g. illness, accommodations, etc.), you may me at [maria.tackett\@duke.edu](mailto:maria.tackett@duke.edu). **If you email me, please include "STA 221" in the subject line.** Barring extenuating circumstances, I will respond to STA 221 emails within 48 hours Monday - Friday. Response time may be slower for emails sent Friday evening - Sunday.

## Academic support

The [Academic Resource Center](https://arc.duke.edu/) (the ARC) offers services to support students academically during their undergraduate careers at Duke. The ARC can provide support with time management, academic skills and strategies, course-specific tutoring, presentation skills, public speaking, and more. ARC services are available free to all Duke undergraduate students studying any discipline. Learn more:

-   [Learning Consultations](https://arc.duke.edu/learning-consultations/) – time management, study strategies, learning preferences, and more

-   [VOICE Lab](https://arc.duke.edu/voice-lab/) – strengthen public speaking, practice presentations, and more

You can contact the Academic Resource Center by phone at (919) 684-5917, by email at [theARC\@duke.edu,](mailto:theARC@duke.edu) or by visiting <http://arc.duke.edu/>.

## Mental health and wellbeing resources

-   [DukeReach](https://students.duke.edu/wellness/dukereach/) provides comprehensive outreach services to support students in managing all aspects of wellbeing, including referrals and follow-up services for students who are experiencing significant challenges related to mental health, physical health, social adjustment, and/or a variety of other stressors. You can contact the DukeReach team at [dukereach\@duke.edu](mailto:dukereach@duke.edu) and/or submit a referral at [support.students.duke.edu](https://support.students.duke.edu/). 

-   [Counseling and Psychological Services (CAPS)](https://students.duke.edu/wellness/caps/) offers counseling services to Duke students including virtual appointments, and referrals in the community. You do not need an appointment for an initial assessment. You may walk in or call 919-660-1000 to get started. Hours: Monday-Friday 9:00am - 4:00pm. After hours counseling services are available at no additional cost to students, you can call: 919-660-1000 Option 2.

-   [TimelyCareLinks to an external site.](https://app.timelycare.com/auth/login?campaign=vanitylink) (formerly known as Blue Devils Care) is an online platform that is a convenient, confidential, and free way for Duke students to receive 24/7 mental health support through TalkNow and scheduled counseling.

-   [Duke Student Health](https://students.duke.edu/wellness/studenthealth/) offers a wide range of healthcare services for all Duke students, many of which are covered by the student health fee. To make an appointment call (919) 681-9355. Hours: Monday - Friday, 8am - 4:30pm, Thursday 9am - 4:30pm. Closed from 12-12:30 each day.

## Technology accommodations

Highly aided students who have limited access to computers may request loaner laptops through the [DukeLIFE Technology Assistance Program](https://dukelife.duke.edu/technology-assistance-program/). Please note that supplies are limited.

Note that we will be using Duke's computational resources in this course. These resources are freely available to you. As long as your computer can connect to the internet and open a browser window, you can perform the necessary computing for this course. All software we use is open-source and/or freely available.

## Course materials costs

There are no costs associated with this course. All readings will come from freely available, open resources (open-source textbooks, journal articles, etc.).

## Assistance with Zoom or Canvas

For technical help with Canvas or Zoom, contact the Duke OIT Service Desk at [oit.duke.edu/help](https://oit.duke.edu/help). You can also access the self-service help documentation for Zoom [here](https://oit.duke.edu/help/articles/kb0029318) and for Canvas [here](https://go.canvas.duke.edu/students-0/).

Zoom will be used for online office hours as well as as a backup option should we need to hold the course online instead of in person.
