---
title: STA 221 Syllabus
subtitle: Spring 2026
format:
  html: default
  pdf: default
---

## Course info

### Class meetings

See Canvas for class meeting times and locations.

### Teaching team

| Name                | Role       |
|---------------------|------------|
| Prof. Maria Tackett | Instructor |
| Cathy Lee           |            |
| Krish Bansal        |            |
| Xueyan Hu           |            |
| Allison Yang        |            |
| Cathy Lee           |            |

**Office hours times and locations on Canvas.**

## Course description

In STA 221, students will learn how linear and logistic regression models are used to explore multivariable relationships, apply these methods to answer relevant and engaging questions using a data-driven approach, and learn the mathematical underpinnings of the models. Students will develop computing skills to implement a reproducible data analysis workflow and gain experience communicating statistical results. Throughout the semester, students will work on a team project where they will develop a research question, answer it using methods learned in the course, and share results through a written report and presentation.

Topics include applications of linear and logistic regression, analysis of variance, model diagnostics, and model selection. Regression parameter estimation via maximum likelihood least squares will also be discussed. Students will gain experience using the computing tools R and GitHub to analyze real-world data from a variety of fields.

### Prerequisites

Either any STA 100-level course or STA 230, 231, or 240L and MATH 216, 218, or 221. The recommended co-requisite is STA 230, 231, or 240L. Interested students with different backgrounds should seek instructor consent.

## Course learning objectives

By the end of the semester, you will be able to...

-   analyze data to explore real-world multivariable relationships.
-   fit, interpret, and draw conclusions from linear and logistic regression models.
-   implement a reproducible analysis workflow using R for analysis, Quarto to write reports and GitHub for version control and collaboration.
-   explain the mathematical foundations of linear and logistic regression.
-   effectively communicate statistical results to a general audience.
-   assess the ethical considerations and implications of analysis decisions.

## Course materials

Most of the reading is in this course will come from *Introduction to Regression Analysis: A Data Science Approach*. It is freely available online ([introregression.netlify.app](https://introregression.netlify.app)). Readings from this text and other sources will be posted under the "prepare" column on the course schedule. We will use the statistical software R. Students will be able to access R through Docker containers provided by Duke Office of Information Technology. See the [computing page](computing-access.qmd) for more information.

## Course community

### Inclusive community

It is my intent that students from all diverse backgrounds and perspectives be well-served by this course, that students' learning needs be addressed both in and out of class, and that the diversity that the students bring to this class be viewed as a resource, strength, and benefit. It is my intent to present materials and activities that are respectful of diversity and in alignment with [Duke's Commitment to Diversity and Inclusion](https://provost.duke.edu/initiatives/commitment-to-diversity-and-inclusion). Your suggestions are encouraged and appreciated. Please let me know ways to improve the effectiveness of the course for you personally, or for other students or student groups.

Furthermore, I would like to create a learning environment for my students that supports a diversity of thoughts, perspectives and experiences, and honors your identities. To help accomplish this:

-   If you feel like your performance in the class is being impacted by your experiences outside of class, please don't hesitate to come and talk with me. If you prefer to speak with someone outside of the course, your academic dean is an excellent resource.
-   I (like many people) am still in the process of learning about diverse perspectives and identities. If something was said in class (by anyone) that made you feel uncomfortable, please let me or a member of the teaching team know.

### Pronouns

Using pronouns can help foster a respectful campus environment where all community members can thrive. Sharing pronouns is always optional for members of the Duke community. If you would like to share yours, you can update them in DukeHub. You can learn more at the [DukeHub & Zoom Tutorials](https://students.duke.edu/belonging/icr/csgd/pronouns/dukehub-zoom/).

### Accessibility

If there is any portion of the course that is not accessible to you due to challenges with technology or the course format, please let me know so we can make appropriate accommodations.

The [Student Disability Access Office (SDAO)](https://access.duke.edu/students) is available to ensure that students are able to engage with their courses and related assignments. Students should be in touch with the Student Disability Access Office to [request or update accommodations](https://access.duke.edu/requests) under these circumstances.

### Communication

All lecture notes, assignment instructions, an up-to-date schedule, and other course materials may be found on the course website, [sta221-sp26.netlify.app](https://sta221-sp26.netlify.app).

Links to Zoom meetings may be found in Canvas. Periodic announcements will be sent via email and will also be available through Ed Discussion and Canvas Announcements. Please check your email regularly to ensure you have the latest announcements for the course.

### Email

If you have questions about assignment extensions, accommodations, or any other matter not appropriate for the class discussion forum, please email me directly at [maria.tackett\@duke.edu](mailto:maria.tackett@duke.edu). **If you email me, please include "STA 221" in the subject line.** Barring extenuating circumstances, I will respond to STA 221 emails within 48 hours Monday - Friday. Response time may be slower for emails sent Friday evening - Sunday.

## Five tips for success

The TAs and I will provide materials, answer questions, and provide guidance to help you learn the material in this course. Below are five things you can do to be successful in STA 221:

1.  Complete all "prepare" readings and tasks before class.

2.  Actively participate and engage in lectures and labs.

3.  Ask questions frequently during lecture, in office hours, on Ed Discussion, and among your classmates.

4.  Complete all homework and lab and ask your self "why" questions ask you go through the steps to complete each exercise.

5.  Stay current with the course material, as each new concept builds on previous ones.

## Getting help in the course

-   If you have a question during lecture or lab, feel free to ask it! There are likely other students with the same question, so by asking you will create a learning opportunity for everyone.
-   The teaching team is here to help you be successful in the course. You are encouraged to attend *office hours*[^1] to ask questions about the course content and assignments. Many questions are most effectively answered as you discuss them with others, so office hours are a valuable resource. You are encouraged to use them!
-   Outside of class and office hours, any general questions about course content or assignments should be posted on the class discussion forum Ed Discussion. There is a chance another student has already asked a similar question, so please check the other posts in Ed Discussion before adding a new question. If you know the answer to a question posted in the discussion forum, you are encouraged to respond!

[^1]: Office hours are times the teaching team set aside each week to meet with students.

Check out the [Support](support.qmd) page for more resources.

## What to expect in the course

### Lectures and labs

Lectures and labs are designed to be interactive, so you gain experience applying new concepts and learning from each other. My role as instructor is to introduce you to new methods, tools, and techniques, but it is up to you to take them and make use of them. A lot of what you do in this course will involve writing code, and coding is a skill that is best learned by doing. Therefore, as much as possible, you will be working on a variety of tasks and activities during the lectures and labs. You are expected to prepare for class by completing assigned readings, attend all lecture and lab sessions, and meaningfully contribute to in-class exercises and discussion.

You are expected to bring a laptop, tablet, or any device with internet and a keyboard to each class so that you can participate in the in-class exercises. Please make sure your device is fully charged before you come to class, because the number of outlets in the classroom will not be sufficient to accommodate everyone.

### Teams

You will be assigned to a team towards the beginning of the semester. You are encouraged to sit with your teammates in lecture and you will also work with them in the lab sessions. All team members are expected to contribute equally to the completion of the group activities, labs and the final project. You will be asked to complete teamwork evaluations and self-reflections throughout the semester. Failure to adequately contribute to an assignment can result in a penalty to your score relative to the team's overall mark.

You are expected to make use of the provided GitHub repository as the central collaborative platform. Commits to this repository will be used as one of several metrics of each team member's relative contribution for each project.

## Activities & Assessment

You will be assessed based on the following components: labs, homework, exams, and a final project.

### Labs

In labs, you will apply the concepts discussed in lecture to a variety of data analysis scenarios, with a focus on the computation and communication. Most lab assignments will be completed in teams, and all team members are expected to contribute equally to the completion of each assignment. You are expected to use the team's Git repository in the course's GitHub organization as the central platform for collaboration. Commits to this repository will be used as a metric of each team member's relative contribution for each lab, and there will be periodic peer evaluation on the team collaboration. Lab assignments will be completed using Quarto, correspond to an appropriate GitHub repository, and submitted for grading in Gradescope.

*Labs will be graded based on completion and workflow. The lowest lab grade will be dropped at the end of the semester.*

### Homework

In homework, you will apply what you've learned during lecture and lab to complete data analysis exercises and explain the underlying mathematics. You may discuss homework assignments with other students; however, homework should be completed and submitted individually. Similar to lab assignments, homework must be typed up using Quarto and GitHub and submitted as a PDF in Gradescope.

One homework assignment will be dedicated to a ***statistics experience***. The statistics experience is an opportunity to engage with statistics and data science outside of the classroom through podcasts, books, seminars, data analysis competitions, and other activities. As you complete these experiences, the goal is to consider how the material you're learning in the course connects with society more broadly.

*The lowest homework grade will be dropped at the end of the semester.*

### Exams

There will be two midterm exams and one final exam in this course. Each midterm exam will include a closed-note in-class component and an open-note take-home component. Through these exams you have the opportunity to demonstrate what you've learned in the course thus far. The exams will focus on both conceptual understanding of the applied and mathematical content and application through analysis and computational tasks. The final exam will be a cumulative closed-note in-class exam during the final exam period set by the university. The final exam will be completed on paper (no computing) and will focus on applied and mathematical content. The content on each exam will be based on the content in reading assignments, lectures, labs, and homework. More detail about the exams will be given during the semester.

There are no make-up exams. If you miss Exam 01 or Exam 02 due to a reason documented by a Dean's Excuse, the final exam score will replace the missed exam score. If you miss the final exam due to a reason documented by a Dean's Excuse, you will receive an "Incomplete" in the course and take the final exam at a later date.

For students who take all three exams, the final exam score will replace the lower of the two mid-term scores, if the final exam score is higher than the Exam 01 and/or Exam 02 score.

### Project

The purpose of the final project is to apply what you've learned to analyze a data-driven research question of your choice. The project will be completed with your lab teams, and each team will present their work through a written report and presentation. More information about the project will be provided during the semester. You can learn more on the [Project](project.qmd) page.

## Grading

The final course grade will be calculated as follows:

<center>

| Category      | Percentage |
|---------------|------------|
| Homework      | 15%        |
| Labs          | 10%        |
| Exam 01       | 20%        |
| Exam 02       | 20%        |
| Final Exam    | 20%        |
| Final project | 15%        |

</center>

<br>

The final letter grade will be determined based on the following thresholds:

<center>

| Letter Grade | Final Course Grade |
|--------------|--------------------|
| A            | \>= 93             |
| A-           | 90 - 92.99         |
| B+           | 87 - 89.99         |
| B            | 83 - 86.99         |
| B-           | 80 - 82.99         |
| C+           | 77 - 79.99         |
| C            | 73 - 76.99         |
| C-           | 70 - 72.99         |
| D+           | 67 - 69.99         |
| D            | 63 - 66.99         |
| D-           | 60 - 62.99         |
| F            | \< 60              |

</center>

## Course policies

### Duke Community Standard

All students must adhere to the [Duke Community Standard(DCS)](https://studentaffairs.duke.edu/conduct/about-us/duke-community-standard): Duke University is a community dedicated to scholarship, leadership, and service and to the principles of honesty, fairness, and accountability. Citizens of this community commit to reflect upon these principles in all academic and non-academic endeavors, and to protect and promote a culture of integrity.

To uphold the Duke Community Standard, students agree:

> -   I will not lie, cheat, or steal in my academic endeavors;
> -   I will conduct myself honorably in all my endeavors;and
> -   I will act if the Standard is compromised.

<iframe width="560" height="315" src="https://www.youtube.com/embed/_KN97j30ST4" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>

</iframe>

### Academic honesty

**TL;DR: Don't cheat!**

-   The homework assignments must be completed individually and you are welcomed to discuss the assignment with classmates at a high level (e.g., discuss what's the best way for approaching a problem, what functions are useful for accomplishing a particular task, etc.). However you may not directly share answers to homework questions (including any code) with anyone other than myself and the teaching assistants.

-   You may not discuss or otherwise work with others on the exams. Unauthorized collaboration or using unauthorized materials will be considered a violation for all students involved. More details will be given closer to the exam date.

-   For the projects and team labs, collaboration within teams is not only allowed, but expected. Communication between teams at a high level is also allowed however you may not share code or components of the project or team labs across teams.

-   **Reusing code**: Unless explicitly stated otherwise, you may make use of online resources (e.g. StackOverflow) for coding examples on assignments. If you directly use code from an outside source (or use it as inspiration), you must explicitly cite where you obtained the code. Any recycled code that is discovered and is not explicitly cited will be treated as plagiarism.

-   **Use of artificial intelligence (AI)**: You should treat AI tools, such as ChatGPT, the same as other online resources. There are two guiding principles that govern how you can use AI in this course:[^2] (1) *Cognitive dimension:* Working with AI should not reduce your ability to think clearly. We will practice using AI to facilitate---rather than hinder---learning. (2) *Ethical dimension***:** Students using AI should be transparent about their use and make sure it aligns with academic integrity.

    -   **AI tools for code:** You may make use of the technology for coding examples on assignments; if you do so, you must explicitly cite where you obtained the code. Any recycled code that is discovered and is not explicitly cited will be treated as plagiarism. You may use [these guidelines](https://guides.lib.monash.edu/c.php?g=219786&p=6972087) for citing AI-generated content.

    -   **No AI tools for narrative:** Unless instructed otherwise, AI is [**not**]{.underline} permitted for writing narrative that is copy and pasted into the assignment. In general, you may use AI as a resource as you complete assignments but not to answer the exercises for you. You are ultimately responsible for the work you turn in; it should reflect your understanding of the course content.

[^2]: These guiding principles are based on [*Course Policies related to ChatGPT and other AI Tools*](https://docs.google.com/document/d/1WpCeTyiWCPQ9MNCsFeKMDQLSTsg1oKfNIH6MzoSFXqQ/preview) developed by Joel Gladd, Ph.D.[↩︎](https://sta101-f23.github.io/course-syllabus.html#fnref1)

If you are unsure if the use of a particular resource complies with the academic honesty policy, please ask a member of the teaching team.

Regardless of course delivery format, it is the responsibility of all students to understand and follow all Duke policies, including academic integrity (e.g., completing one's own work, following proper citation of sources, adhering to guidance around group work projects,and more). Ignoring these requirements is a violation of the Duke Community Standard. Any questions and/or concerns regarding academic integrity can be directed to the Office of Student Conduct and Community Standards at [conduct\@duke.edu](mailto:conduct@duke.edu).

### Late work policy

The due dates for assignments are there to help you keep up with the course material and to ensure the teaching team can provide feedback in a timely manner. We understand that things come up periodically that could make it difficult to submit an assignment by the deadline. *Note that the lowest homework and lab assignment will be dropped to accommodate such circumstances.*

-   There is no late work permitted on lab assignments. These are graded for completion, so a lab assignment will be graded as "Not complete" if it is submitted after the deadline.

-   Homework and labs may be submitted up to 2 days late. There will be a 5% deduction for each 24-hour period the assignment is late.

-   The late work policy for exams will be provided with the exam instructions.

-   The late work policy for the project will be provided with the project instructions.

### Waiver for extenuating circumstances

If there are circumstances that prevent you from completing a homework assignment by the stated due date, you may email me at [maria.tackett\@duke.edu](maria.tackett@duke.edu) [**before the deadline**]{.underline} to waive the late penalty. In your email, you only need to request the waiver; you do not need to provide explanation. *This waiver may only be used once in the semester, so only use it for a truly extenuating circumstance.*

If there are circumstances that are having a longer-term impact on your academic performance, please let your academic dean know, as they can be a resource.

### Regrade Requests

Regrade requests must be submitted on Gradescope within a week of when an assignment is returned. Regrade requests will be considered if there was an error in the grade calculation or if you feel a correct answer was mistakenly marked as incorrect. Requests to dispute the number of points deducted for an incorrect response will not be considered. Note that by submitting a regrade request, the entire question will be graded which could potentially result in losing points.

*No grades will be changed after the final exam has been administered.*

### Attendance policy

Every student is expected to attend and participate in lecture and labs. There may be times, however, when you cannot attend class. Lecture recordings are available upon request for students who have an excused absence. See the [Lecture recording request] policy for more detail. If you miss a lecture, make sure to review the material and complete the application exercise, if applicable, before the next lecture.

Labs are dedicated to completing the lab assignment and collaborating with your lab team. If you miss a lab session, make sure to communicate with your lab TA and teammates about how you can make up your contribution. If you know you're going to miss a lab session and you're feeling well enough to do so, notify your lab TA and teammates ahead of time.

More details on Trinity attendance policies are available [here](https://trinity.duke.edu/undergraduate/academic-policies/class-attendance-and-missed-work).

### Lecture recording request

Lectures will be recorded on Panopto and will be made available to students with an excused absence upon request. Videos shared with such students will be available for a week after the lecture date. To request a particular lecture's video, please fill out the form at the link below. Please submit the form within 24 hours of missing lecture to ensure you have sufficient time to watch the recording. Please also make sure that any official documentation, such as incapacitation forms, Dean's excuses, NOVAPs, and quarantine/removal from class notices from student health are also uploaded to the form.

🔗 <https://forms.office.com/r/RW2TTPrsQq>

About one week before each exam, the class recordings will be available to all students. These recordings will be available until the start of the exam.

## Accommodations

### Academic accommodations

If you need accommodations for this class, you will need to register with the Student Disability Access Office (SDAO) and provide them with documentation related to your needs. SDAO will work with you to determine what accommodations are appropriate for your situation. Please note that accommodations are not retroactive and disability accommodations cannot be provided until a Faculty Accommodation Letter has been given to me. Please contact SDAO for more information: [sdao\@duke.edu](mailto:sdao@duke.edu) or [access.duke.edu](https://access.duke.edu).

### **Religious accommodations**

Students are permitted by university policy to be absent from class to observe a religious holiday. Accordingly, Trinity College of Arts & Sciences and the Pratt School of Engineering have established procedures to be followed by students for notifying their instructors of an absence necessitated by the observance of a religious holiday. Please submit requests for religious accommodations at the beginning of the semester so that we can work to make suitable arrangements well ahead of time. You can find the policy and relevant notification form here: [trinity.duke.edu/undergraduate/academic-policies/religious-holidays](https://trinity.duke.edu/undergraduate/academic-policies/religious-holidays)

## Academic support

### Academic Resource Center

The [Academic Resource Center](https://arc.duke.edu/) (the ARC) offers services to support students academically during their undergraduate careers at Duke. The ARC can provide support with time management, academic skills and strategies, course-specific tutoring, presentation skills, public speaking, and more. ARC services are available free to all Duke undergraduate students studying any discipline. Learn more:

-   [Learning Consultations](https://arc.duke.edu/learning-consultations/) – time management, study strategies, learning preferences, and more

-   [VOICE Lab](https://arc.duke.edu/voice-lab/) – strengthen public speaking, practice presentations, and more

You can contact the Academic Resource Center by phone at (919) 684-5917, by email at [theARC\@duke.edu,](mailto:theARC@duke.edu) or by visiting <http://arc.duke.edu/>.

## Important dates

-   **January 7**: Classes begin
-   **January 19**: Martin Luther King Jr. Day holiday.
-   **January 21**: Drop/Add ends
-   **March 9 - 13**: Spring break
-   **March 25**: Last day to withdraw with "W"
-   **April 22**: Classes end
-   **April 23-26**: Reading period
-   **April 27 - May 2**: Final exam period

[Click here](https://registrar.duke.edu/2025-2026-academic-calendar/) for the full Duke academic calendar.
